server:
  port: 9000
  session:
    cookie:
      name: UISESION
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: client-id
      client-secret: secret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/api/v1/principal

zuul:
  routes:
    user:
      path: /user/**
      url: http://localhost:8080/api/v1/principal


