spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_store_prod
    username: store_user_prod
    password: springstore
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect